version: '3.8'
services:
  movies:
    image: harshaara/paytmmovies:latest
    ports:
      - "81:80"
    
    deploy:
      replicas: 3

  train:
    image: harshaara/paytmtrain:latest
    ports:
      - "82:80"
    
    deploy:
      replicas: 3
  dth:
    image: harshaara/paytmdth:latest
    ports:
      - "83:80"
    

    deploy:
      replicas: 3

  recharge:
    image: harshaara/paytmrecharge:latest
    ports:
      - "84:80"
   
    deploy:
      replicas: 3
