version: '3.8'
services:
  movies:
    image: harshaara/paytmmovies:latest
    ports:
      - "81:80"
    volumes:
      - "movies"
    deploy:
      replicas: 3

  train:
    image: harshaara/paytmtrain:latest
    ports:
      - "82:80"
    volumes:
      - "train"
    deploy:
      replicas: 3
  dth:
    image: harshaara/paytmdth:latest
    ports:
      - "83:80"
    volumes:
      - "dth"

    deploy:
      replicas: 3

  recharge:
    image: harshaara/paytmrecharge:latest
    ports:
      - "84:80"
    volumes:
      - "recharge"

    deploy:
      replicas: 3
